sudo: false
language: node_js
#cache:
#  directories:
#    - node_modules
notifications:
  email: false
node_js:
  - '4'
  - '5'
  - '6'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  code_climate:
      repo_token: ${CODECLIMATE_REPO_TOKEN}
before_script:
  - snyk auth ${SNYK_TOKEN}
script:
  - npm run security_check
  - npm run test
  - npm run lint
