sudo: false
language: node_js
#cache:
#  directories:
#    - node_modules
notifications:
  email: false
node_js:
  - '0.12'
  - '4'
  - '5'
#before_install:
#  - npm i -g npm@^2.0.0
#  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
before_script:
  - node_modules/.bin/snyk auth ${SNYK_TOKEN}
script:
  - npm security_check
  - npm lint
  - npm test
#after_success:
#  - python scripts/travis_after_all.py
#  - export $(cat .to_export_back)
#  - npm run semantic-release
